spring:
  # Spring连接DM数据库驱动
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.56.162:5236/ocean-online
    username: root
    password: 1111111111


  # 指定JPA配置
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: false
    database-platform: org.hibernate.dialect.DmDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
  jackson:
    serialization:
      indent_output: false



# // DM的JDBC URL编写方式：jdbc:dm://主机名称:连接端口/数据库的名称
# // 执行数据库操作之前要在数据库管理系统上创建一个数据库，名字自己定
